package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/gophergala2016/wwcdc_01/models"
)

/*AddScreenshotOK success response

swagger:response addScreenshotOK
*/
type AddScreenshotOK struct {
}

// NewAddScreenshotOK creates AddScreenshotOK with default headers values
func NewAddScreenshotOK() *AddScreenshotOK {
	return &AddScreenshotOK{}
}

// WriteResponse to the client
func (o *AddScreenshotOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
}

/*AddScreenshotDefault unexpected error

swagger:response addScreenshotDefault
*/
type AddScreenshotDefault struct {
	_statusCode int

	// In: body
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewAddScreenshotDefault creates AddScreenshotDefault with default headers values
func NewAddScreenshotDefault(code int) *AddScreenshotDefault {
	if code <= 0 {
		code = 500
	}

	return &AddScreenshotDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add screenshot default response
func (o *AddScreenshotDefault) WithStatusCode(code int) *AddScreenshotDefault {
	o._statusCode = code
	return o
}

// WithPayload adds the payload to the add screenshot default response
func (o *AddScreenshotDefault) WithPayload(payload *models.ErrorModel) *AddScreenshotDefault {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *AddScreenshotDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
