package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	"github.com/gophergala2016/wwcdc_01/models"
)

// NewAddLearningResourceParams creates a new AddLearningResourceParams object
// with the default values initialized.
func NewAddLearningResourceParams() AddLearningResourceParams {
	var ()
	return AddLearningResourceParams{}
}

// AddLearningResourceParams contains all the bound params for the add learning resource operation
// typically these are obtained from a http.Request
//
// swagger:parameters addLearningResource
type AddLearningResourceParams struct {
	/*LearningResource to add to the store
	  Required: true
	  In: body
	*/
	LearningResource *models.LearningResource
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AddLearningResourceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	var body models.LearningResource
	if err := route.Consumer.Consume(r.Body, &body); err != nil {
		res = append(res, errors.NewParseError("learningResource", "body", "", err))
	} else {
		if err := body.Validate(route.Formats); err != nil {
			res = append(res, err)
		}

		if len(res) == 0 {
			o.LearningResource = &body
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
