package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	"github.com/gophergala2016/wwcdc_01/models"
)

// NewAddReviewParams creates a new AddReviewParams object
// with the default values initialized.
func NewAddReviewParams() AddReviewParams {
	var ()
	return AddReviewParams{}
}

// AddReviewParams contains all the bound params for the add review operation
// typically these are obtained from a http.Request
//
// swagger:parameters addReview
type AddReviewParams struct {
	/*Review to add
	  Required: true
	  In: body
	*/
	Review *models.Review
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AddReviewParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	var body models.Review
	if err := route.Consumer.Consume(r.Body, &body); err != nil {
		res = append(res, errors.NewParseError("review", "body", "", err))
	} else {
		if err := body.Validate(route.Formats); err != nil {
			res = append(res, err)
		}

		if len(res) == 0 {
			o.Review = &body
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
