package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// FindLanguagesHandlerFunc turns a function with the right signature into a find languages handler
type FindLanguagesHandlerFunc func() middleware.Responder

// Handle executing the request and returning a response
func (fn FindLanguagesHandlerFunc) Handle() middleware.Responder {
	return fn()
}

// FindLanguagesHandler interface for that can handle valid find languages params
type FindLanguagesHandler interface {
	Handle() middleware.Responder
}

// NewFindLanguages creates a new http.Handler for the find languages operation
func NewFindLanguages(ctx *middleware.Context, handler FindLanguagesHandler) *FindLanguages {
	return &FindLanguages{Context: ctx, Handler: handler}
}

/*FindLanguages swagger:route GET /languages findLanguages

Returns all languages

*/
type FindLanguages struct {
	Context *middleware.Context
	Handler FindLanguagesHandler
}

func (o *FindLanguages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle() // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
