package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/gophergala2016/wwcdc_01/models"
)

/*FindUserByIDOK user response

swagger:response findUserByIdOK
*/
type FindUserByIDOK struct {

	// In: body
	Payload *models.User `json:"body,omitempty"`
}

// NewFindUserByIDOK creates FindUserByIDOK with default headers values
func NewFindUserByIDOK() *FindUserByIDOK {
	return &FindUserByIDOK{}
}

// WithPayload adds the payload to the find user by id o k response
func (o *FindUserByIDOK) WithPayload(payload *models.User) *FindUserByIDOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *FindUserByIDOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FindUserByIDDefault unexpected error

swagger:response findUserByIdDefault
*/
type FindUserByIDDefault struct {
	_statusCode int

	// In: body
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewFindUserByIDDefault creates FindUserByIDDefault with default headers values
func NewFindUserByIDDefault(code int) *FindUserByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &FindUserByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find user by id default response
func (o *FindUserByIDDefault) WithStatusCode(code int) *FindUserByIDDefault {
	o._statusCode = code
	return o
}

// WithPayload adds the payload to the find user by id default response
func (o *FindUserByIDDefault) WithPayload(payload *models.ErrorModel) *FindUserByIDDefault {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *FindUserByIDDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
