package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/go-swagger/go-swagger/spec"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewGophergalaLearningResourcesAPI creates a new GophergalaLearningResources instance
func NewGophergalaLearningResourcesAPI(spec *spec.Document) *GophergalaLearningResourcesAPI {
	o := &GophergalaLearningResourcesAPI{
		spec:            spec,
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
	}

	return o
}

/*GophergalaLearningResourcesAPI the gophergala learning resources API */
type GophergalaLearningResourcesAPI struct {
	spec            *spec.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer httpkit.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer httpkit.Producer

	// AddLearningResourceHandler sets the operation handler for the add learning resource operation
	AddLearningResourceHandler AddLearningResourceHandler
	// AddReviewHandler sets the operation handler for the add review operation
	AddReviewHandler AddReviewHandler
	// AddScreenshotHandler sets the operation handler for the add screenshot operation
	AddScreenshotHandler AddScreenshotHandler
	// AddUserHandler sets the operation handler for the add user operation
	AddUserHandler AddUserHandler
	// DeleteLearningResourceHandler sets the operation handler for the delete learning resource operation
	DeleteLearningResourceHandler DeleteLearningResourceHandler
	// DeleteReviewHandler sets the operation handler for the delete review operation
	DeleteReviewHandler DeleteReviewHandler
	// DeleteUserHandler sets the operation handler for the delete user operation
	DeleteUserHandler DeleteUserHandler
	// FindLanguagesHandler sets the operation handler for the find languages operation
	FindLanguagesHandler FindLanguagesHandler
	// FindLearningResourceByIDHandler sets the operation handler for the find learning resource by id operation
	FindLearningResourceByIDHandler FindLearningResourceByIDHandler
	// FindLearningResourcesHandler sets the operation handler for the find learning resources operation
	FindLearningResourcesHandler FindLearningResourcesHandler
	// FindReviewByIDHandler sets the operation handler for the find review by id operation
	FindReviewByIDHandler FindReviewByIDHandler
	// FindReviewsHandler sets the operation handler for the find reviews operation
	FindReviewsHandler FindReviewsHandler
	// FindUserByIDHandler sets the operation handler for the find user by id operation
	FindUserByIDHandler FindUserByIDHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup
}

// SetDefaultProduces sets the default produces media type
func (o *GophergalaLearningResourcesAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *GophergalaLearningResourcesAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// DefaultProduces returns the default produces media type
func (o *GophergalaLearningResourcesAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *GophergalaLearningResourcesAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *GophergalaLearningResourcesAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *GophergalaLearningResourcesAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the GophergalaLearningResourcesAPI
func (o *GophergalaLearningResourcesAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.AddLearningResourceHandler == nil {
		unregistered = append(unregistered, "AddLearningResourceHandler")
	}

	if o.AddReviewHandler == nil {
		unregistered = append(unregistered, "AddReviewHandler")
	}

	if o.AddScreenshotHandler == nil {
		unregistered = append(unregistered, "AddScreenshotHandler")
	}

	if o.AddUserHandler == nil {
		unregistered = append(unregistered, "AddUserHandler")
	}

	if o.DeleteLearningResourceHandler == nil {
		unregistered = append(unregistered, "DeleteLearningResourceHandler")
	}

	if o.DeleteReviewHandler == nil {
		unregistered = append(unregistered, "DeleteReviewHandler")
	}

	if o.DeleteUserHandler == nil {
		unregistered = append(unregistered, "DeleteUserHandler")
	}

	if o.FindLanguagesHandler == nil {
		unregistered = append(unregistered, "FindLanguagesHandler")
	}

	if o.FindLearningResourceByIDHandler == nil {
		unregistered = append(unregistered, "FindLearningResourceByIDHandler")
	}

	if o.FindLearningResourcesHandler == nil {
		unregistered = append(unregistered, "FindLearningResourcesHandler")
	}

	if o.FindReviewByIDHandler == nil {
		unregistered = append(unregistered, "FindReviewByIDHandler")
	}

	if o.FindReviewsHandler == nil {
		unregistered = append(unregistered, "FindReviewsHandler")
	}

	if o.FindUserByIDHandler == nil {
		unregistered = append(unregistered, "FindUserByIDHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *GophergalaLearningResourcesAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *GophergalaLearningResourcesAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]httpkit.Authenticator {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *GophergalaLearningResourcesAPI) ConsumersFor(mediaTypes []string) map[string]httpkit.Consumer {

	result := make(map[string]httpkit.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *GophergalaLearningResourcesAPI) ProducersFor(mediaTypes []string) map[string]httpkit.Producer {

	result := make(map[string]httpkit.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *GophergalaLearningResourcesAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

func (o *GophergalaLearningResourcesAPI) initHandlerCache() {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/learning-resources"] = NewAddLearningResource(o.context, o.AddLearningResourceHandler)

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/reviews"] = NewAddReview(o.context, o.AddReviewHandler)

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/screenshot/{id}"] = NewAddScreenshot(o.context, o.AddScreenshotHandler)

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users"] = NewAddUser(o.context, o.AddUserHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers[strings.ToUpper("DELETE")] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/learning-resources/{id}"] = NewDeleteLearningResource(o.context, o.DeleteLearningResourceHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers[strings.ToUpper("DELETE")] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/reviews/{id}"] = NewDeleteReview(o.context, o.DeleteReviewHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers[strings.ToUpper("DELETE")] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users/{id}"] = NewDeleteUser(o.context, o.DeleteUserHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/languages"] = NewFindLanguages(o.context, o.FindLanguagesHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/learning-resources/{id}"] = NewFindLearningResourceByID(o.context, o.FindLearningResourceByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/learning-resources"] = NewFindLearningResources(o.context, o.FindLearningResourcesHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/reviews/{id}"] = NewFindReviewByID(o.context, o.FindReviewByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/reviews"] = NewFindReviews(o.context, o.FindReviewsHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{id}"] = NewFindUserByID(o.context, o.FindUserByIDHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *GophergalaLearningResourcesAPI) Serve(builder middleware.Builder) http.Handler {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}

	return o.context.APIHandler(builder)
}
