package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

/*Languages Languages languages

swagger:model Languages
*/
type Languages struct {

	/* Languages languages
	 */
	Languages []string `json:"languages,omitempty"`
}

// Validate validates this languages
func (m *Languages) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLanguages(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Languages) validateLanguages(formats strfmt.Registry) error {

	if swag.IsZero(m.Languages) { // not required
		return nil
	}

	for i := 0; i < len(m.Languages); i++ {

		if err := validate.RequiredString("languages"+"."+strconv.Itoa(i), "body", string(m.Languages[i])); err != nil {
			return err
		}

	}

	return nil
}
